# Description of conda environment for this project.
name: tohu
dependencies:
  - python=3.6
  - ipython
  - jupyter
  - mako
  - pandas
  - pytest
  - pytest-cov
  - python-dateutil
  - pip:
      - nbval
      - yapf
      - tqdm
