version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install PostgreSQL
          command: sudo apt-get update && sudo apt-get install -y postgresql
      - run:
          name: Install Python dependencies
          command: pipenv install --dev
      - run:
          name: Install tohu
          command: pipenv run pip install .
      - run:
          name: Run tests
          command: pipenv run make test
