import pytest
from .exemplar_generators import EXEMPLAR_DERIVED_GENERATORS


@pytest.mark.parametrize("g", EXEMPLAR_DERIVED_GENERATORS)
def test_spawn_derived_generators(g):
    """
    Test that an Apply generator can be spawned and the spawned version produces the same elements.
    """
    num_items = 50

    g.reset(seed=12345)
    g.reset_input_generators(seed=99999)

    # Let g generate a few items
    items_g_pre_spawn = list(g.generate(num_items))

    # Spawn g and let both generate a few more items
    h = g.spawn()
    items_g_post_spawn = list(g.generate(num_items))
    items_h_post_spawn = list(h.generate(num_items))

    # Reset h (including input generators) and re-generate the full list of items
    h.reset(seed=12345)
    h.reset_input_generators(seed=99999)
    items_h_all = list(h.generate(2*num_items))

    # Verify that the items generated by h after spawning
    # as well as the full sets of items are identical.
    assert items_h_post_spawn == items_g_post_spawn
    assert items_h_all == items_g_pre_spawn + items_g_post_spawn
